package com.jbytescanner.engine;

import com.jbytescanner.core.SootManager;
import com.jbytescanner.model.ApiRoute;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import java.util.stream.Collectors;

public class DiscoveryEngine {
    private static final Logger logger = LoggerFactory.getLogger(DiscoveryEngine.class);
    private final List<String> appJars;
    private final List<String> libJars;
    private final File workspaceDir;

    public DiscoveryEngine(List<String> appJars, List<String> libJars, File workspaceDir) {
        this.appJars = appJars;
        this.libJars = libJars;
        this.workspaceDir = workspaceDir;
    }

    public void run() {
        logger.info("Starting Discovery Engine...");
        
        // 1. Init Soot
        SootManager.initSoot(appJars, libJars, false);
        
        // 2. Extract Routes
        RouteExtractor extractor = new RouteExtractor();
        List<ApiRoute> routes = extractor.extract();
        
        logger.info("Found {} API Routes.", routes.size());
        
        // 3. Write Output
        writeApiTxt(routes);
    }

    private void writeApiTxt(List<ApiRoute> routes) {
        File apiFile = new File(workspaceDir, "api.txt");
        List<String> lines = new ArrayList<>();
        String timestamp = LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss"));
        lines.add(String.format("### Generated by JByteScanner at %s | AppJars: %d | LibJars: %d ###", 
                timestamp, appJars.size(), libJars.size()));
        
        lines.addAll(routes.stream()
                .map(ApiRoute::toString)
                .collect(Collectors.toList()));
        
        try {
            Files.write(apiFile.toPath(), lines);
            logger.info("API Dictionary written to: {}", apiFile.getAbsolutePath());
        } catch (IOException e) {
            logger.error("Failed to write api file", e);
        }
    }
}
