package com.jbytescanner.engine;

import com.jbytescanner.core.SootManager;
import com.jbytescanner.model.ApiRoute;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import java.util.stream.Collectors;

public class DiscoveryEngine {
    private static final Logger logger = LoggerFactory.getLogger(DiscoveryEngine.class);
    private final List<String> targetAppJars;
    private final List<String> depAppJars;
    private final List<String> libJars;
    private final File workspaceDir;
    private final List<String> filterAnnotations;

    public DiscoveryEngine(List<String> targetAppJars, List<String> depAppJars, List<String> libJars, File workspaceDir, List<String> filterAnnotations) {
        this.targetAppJars = targetAppJars;
        this.depAppJars = depAppJars;
        this.libJars = libJars;
        this.workspaceDir = workspaceDir;
        this.filterAnnotations = filterAnnotations;
    }

    public void run() {
        logger.info("Starting Discovery Engine...");
        
        // 1. Init Soot
        // For discovery, we usually want to see everything in App Jars, 
        // but strict isolation helps speed up here too if we only care about target packages.
        // However, Discovery is lightweight (no bodies), so we can be more permissive or strict.
        // Let's stick to strict if scanPackages are defined to avoid noise.
        
        List<String> combinedLibs = new ArrayList<>(libJars);
        if (depAppJars != null) combinedLibs.addAll(depAppJars);

        SootManager.initSoot(targetAppJars, combinedLibs, false);
        
        // 2. Extract Routes
        RouteExtractor extractor = new RouteExtractor(filterAnnotations);
        List<ApiRoute> routes = extractor.extract();
        
        logger.info("Found {} API Routes.", routes.size());

        
        // 3. Write Output
        writeApiTxt(routes);
    }

    private void writeApiTxt(List<ApiRoute> routes) {
        File apiFile = new File(workspaceDir, "api.txt");
        List<String> lines = new ArrayList<>();
        String timestamp = LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss"));
        lines.add(String.format("### Generated by JByteScanner at %s | TargetAppJars: %d | LibJars: %d ###", 
                timestamp, targetAppJars.size(), libJars.size()));
        
        lines.addAll(routes.stream()
                .map(ApiRoute::toString)
                .collect(Collectors.toList()));
        
        try {
            Files.write(apiFile.toPath(), lines);
            logger.info("API Dictionary written to: {}", apiFile.getAbsolutePath());
        } catch (IOException e) {
            logger.error("Failed to write api file", e);
        }
    }
}
